"""项目配置"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# THCHS-30
THCHS30_ROOT = ROOT / "data" / "data_thchs30"
THCHS30_TRAIN_DIR = THCHS30_ROOT / "train"
THCHS30_DEV_DIR = THCHS30_ROOT / "dev"

TRAIN_CACHE_DIR = ROOT / "data" / "processed" / "train"
DEV_CACHE_DIR = ROOT / "data" / "processed" / "dev"
CHECKPOINT_DIR = ROOT / "checkpoints"
OUTPUT_DIR = ROOT / "outputs"

# 音频
SAMPLE_RATE = 22050
N_FFT = 1024
HOP_LENGTH = 256
WIN_LENGTH = 1024
N_MELS = 80
MEL_FMIN = 0.0
MEL_FMAX = 8000.0

# 文本
PAD_TOKEN = "_"
EOS_TOKEN = "~"
PUNCTUATION = "，。！？、；：""''（）《》【】…—"

# 模型
SYMBOL_EMBEDDING_DIM = 512
ENCODER_CONV_CHANNELS = 512
ENCODER_KERNEL_SIZE = 5
ENCODER_N_CONV = 3
ENCODER_LSTM_HIDDEN = 256
ATTENTION_RNN_DIM = 1024
ATTENTION_DIM = 128
ATTENTION_LOCATION_N_FILTERS = 32
ATTENTION_LOCATION_KERNEL_SIZE = 31
DECODER_RNN_DIM = 1024
PRENET_DIM = 256
POSTNET_N_CONV = 5
POSTNET_CHANNELS = 512
POSTNET_KERNEL_SIZE = 5
MAX_DECODER_STEPS = 2000
GATE_THRESHOLD = 0.5

# 长音频分段（THCHS-30 短句通常不切分）
SEGMENT_MEL_FRAMES = 512
SEGMENT_TEXT_LEN = 200
GRIFFIN_LIM_ITERS = 60
